{% set name = "qa-noarch-test" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../src

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - qa_noarch_test
  commands:
    - python -c "from qa_noarch_test import main; main()"

about:
  summary: "QA dummy noarch package that prints hello world"
  license: MIT
