{% set name = "qa-noarch-test" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../src

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

  entry_points:
    - qa-noarch-test = qa_noarch_test:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - qa_noarch_test
  commands:
    - qa-noarch-test

about:
  summary: "QA dummy noarch package that prints hello world"
  license: MIT
